YES_HEMOLYTIC = {". Show hemolytic activity",
                 "has hemolytic activity",
                 "Has hemolytic activity",
                 "is more hemolytic than",
                 "has antibacterial and hemolytic activity",
                 "Shows strong hemolytic activity",
                 "Has antimicrobial and hemolytic activities.",
                 "Has hemolytic and antibacterial activities.",
                 "Has hemolytic and antibacterial activity.",
                 "Showes obvious hemolytic activity against human red blood cells",
                 "Also possessed hemolytic activity",
                 "has low or moderate hemolytic activity",
                 "relatively greater hemolytic activity",
                 "exhibits hemolytic activitie",
                 "exhibits hemolytic activity",
                 "and hemolytic activity",
                 "The hemolytic activity against",
                 "also shows hemolytic activities",
                 "Exhibits hemolytic activity",
                 "60% hemolysis",
                 "strong hemolytic activity",
                 "greatest hemolytic activity",
                 "shows hemolytic activities",
                 "It displayed hemolytic activity",
                 "high hemolytic activity",
                 "shows hemolytic activity",
                 "strongly hemolytic",
                 "induce 17 and 21% Rabbit red blood cell hemolysis",
                 "Shows hemolytic activity",
                 "The % hemolytic activity gainst rabbit red cells at 100 µg/ml is 46.13±1.49 %",
                 "The % hemolytic activity gainst rabbit red cells at 100 µg/ml is 18.64±0.25 %",
                 "The % hemolytic activity gainst rabbit red cells at 100 µg/ml is 16.16±3.22 %",
                 "Shows hemolytic activity",
                 "Has lytic, hemolytic and antibacterial activities",
                 "shows moderate hemolytic activities",
                 "moderate hemolytic activity",
                 "also induce hemolysis",
                 "Exhibits diverse biological activities, such as hemorrhage, hemolysis",
                 "This protein induce hemolysis",
                 "This protein may also induce hemorrhage, hemolysis",
                 "Exhibits diverse biological activities, such as hemolysis",
                 "has indirect hemolytic activity",
                 "May also have an ability to induce hemorrhage, hemolysis",
                 "Has potent hemolytic activity",
                 "Has insecticidal and hemolytic activities",
                 "Has modest hemolytic activity",
                 "This protein may also have activities in hemorrhage, hemolysis",
                 "are hemolytic for human red blood cells",
                 "Has strong cytotoxic and hemolytic activities",
                 "Causes hemolysis",
                 "Synthetic peptide exhibits haemolytic activity",
                 "slightly more hemolytic",
                 "Also Has hemolytic",
                 "They have as well hemolytic activity.",
                 "causes hemolysis",
                 "23% hemolytic",
                 "ability to induce hemolysis",
                 "mildly hemolytic",
                 "enhanced the hemolytic activity",
                 "(25% hemolysis at 50 µM)",
                 "(35% hemolysis at 50 µM)",
                 "(22% hemolysis at 50 µM)",
                 "Strongly hemolytic",
                 "Hemolysis observed",
                 "Very strong hemolysis",
                 "Strong hemolysis",
                 "Increased hemolysis",
                 "50% Hemolysis",
                 "55% Hemolysis",
                 "85% Hemolysis",
                 "46% Hemolysis",
                 "24% Hemolysis",
                 "50% cytotoxicity",
                 "50% Cytotoxicity",
                 "50% Cell death",
                 "79% Hemolysis",
                 "48% Hemolysis",
                 "38% Hemolysis",
                 "36% Hemolysis",
                 "96% Hemolysis",
                 "(34 ±2.1)% Hemolysis",
                 "(45±5)% cytotoxicity",
                 "(65±1.5)% Hemolysis",
                 "(91±6.2)% Hemolysis",
                 "(28 ± 3.2)% Hemolysis",
                 "(77.57±4.32)% Degranulation",
                 "(80.43±0.97)% Degranulation",
                 "(29.78±4.24)% Degranulation",
                 "(63.86±10.17)% Degranulation",
                 "(45.99±0.36)% Degranulation",
                 "(56.12±7.98)% Degranulation",
                 "CC50",
                 "(36.7±5.2)% degranulation",
                 "(41.8±7.2)% degranulation",
                 "(19.4±5.3)% degranulation",
                 "(30.1±4.4)% degranulation",
                 "(23.2±5.3)% degranulation",
                 "(36.7±5.2)% degranulation",
                 "89±0.6% Cell death",
                 "42±4.1% Cell death",
                 "89±1.2% Cell death",
                 "43±5.7% Cell death",
                 "55±2.5% Cell death",
                 "(25.1±9.2)% degranulation",
                 "(28.6±5.7)% degranulation",
                 "(22±2.8)% Hemolysis",
"(21.0±3.5) Cytotoxicity",
                 }

YES_HEMOLYTIC2 = list(["%s" % str(n) + "% Hemolysis" for n in range(20, 101)])
YES_HEMOLYTIC3 = list(["%s" % str(n) + "% Cell Death" for n in range(20, 101)])
YES_HEMOLYTIC4 = list(["%s" % str(n) + "% Cytotoxicity" for n in range(20, 101)])
YES_HEMOLYTIC5 = list(["%s" % str(n) + "% cytotoxicity" for n in range(20, 101)])
YES_HEMOLYTIC6 = list(["%s" % str(n) + "% Killing" for n in range(20, 101)])
YES_HEMOLYTIC7 = list(["%s" % str(n) + "% cell death" for n in range(20, 101)])
YES_HEMOLYTIC8 = list(["%s" % str(n) + "% Inhibition" for n in range(20, 101)])
YES_HEMOLYTIC9 = list(["%s" % str(n) + "% degranulation" for n in range(20, 101)])
YES_HEMOLYTIC = list(YES_HEMOLYTIC) + YES_HEMOLYTIC2 + YES_HEMOLYTIC3 + YES_HEMOLYTIC4 + YES_HEMOLYTIC5 + YES_HEMOLYTIC6 + YES_HEMOLYTIC7 + YES_HEMOLYTIC8 + YES_HEMOLYTIC9
YES_HEMOLYTIC = set(YES_HEMOLYTIC)

LITTLE_HEMOLYTIC = {"low hemolytic activity",
                    "showed weak hemolysis activity",
                    "Has a weak hemolytic activity",
                    "The hemolytic activity against human erythrocytes of all peptides tested is relatively weak",
                    "only 2.5% hemolysis",
                    "Has little hemolytic activity",
                    "It has little hemolytic activity",
                    "has a weak hemolytic activity",
                    "has little hemolytic activity",
                    "weak hemolytic activity",
                    "lower hemolytic effect to human erythrocytes",
                    "weak hemolytic activty",
                    "about 1.3% hemolysis",
                    "about 1.1% hemolysis",
                    "Has a very week hemolytic activity",
                    "poor hemolycity activity",
                    "very little hemolytic activity",
                    "induces 1.5 and 2.1% hemolysis",
                    "Low hemolytic toxicity",
                    "little hemolytic activity",
                    "Slight hemolytic activity",
                    "limited hemolytic activity",
                    "6% hemolytic",
                    "slight hemolytic effect",
                    "big loss of hemolysis activity",
                    "Little hemolysis",
                    "Weak hemolytic activity",
                    "Low hemolytic activity",
                    "Low hemolysis",
                    "Mild hemolytic activity",
                    "Very little hemolysis",
                    "Poor hemolytic",
                    "<5% Hemolysis",
                    "5% Hemolysis",
                    "2% Hemolysis",
                    "7% Hemolysis",
                    "3% Hemolysis",
                    "9% Hemolysis",
                    "16% Hemolysis",
                    "18% Hemolysis",
                    "14% Hemolysis",
                    "8% Hemolysis",
                    "<8% Hemolysis",
                    "4% Hemolysis",
                    "<10%  Hemolysis",
                    "(12±2)% cytotoxicity",
                    "(1.5±1.1)% degranulation",
                    "(1.7±0.9)% degranulation",
                    "(0.8±0.6)% degranulation",
                    "(2.5±1.3)% degranulation",
                    "15% degranulation",
                    "(13.6±4.5) Cytotoxicity",
                    "(11.2±2.1) Cytotoxicity",
                    "(14.33±4.86)% Degranulation",
                    "(4.43±0.35)% Degranulation",
                    "(9.3±2.8)% degranulation"
                    "(2.9±1.5)% degranulation",
                    "(91.7±3.56) Viability",
                    "(93.7±2.04) Viability",
                    "(92.2±1.83) Viability",
                    "(37.5±1.9)% Hemolysis",
"(23.5±1.3)% Hemolysis",
"17±1.5% Cell death",
"0.45±0.10",
"(2.6±1.3)% degranulation",
"(2.9±1.5)% degranulation",
"(15.2±4.9)% degranulation",
"(7.7±2.6)% degranulation",
"(13.3±4.8)% degranulation",
"(4.5±2.1)% degranulation",
"(1.6±1.2)% degranulation",
"(15.5±7.3)% degranulation",
"(9.2±0.7)% degranulation",
"(1.6±0.5)% degranulation",
"(9.3±2.8)% degranulation",
"(2.9±1.5)% degranulation",
"(15.04±2.29)% Degranulation",
"(7.31±1.63)% Degranulation",
"(8.87±1.63)% Degranulation",
"(10.94±1.49)% Degranulation",
"(1±0.1)% Hemolysis",
"(3.5±1.6)% degranulation",
" (6.2±2.4)% degranulation",
"(17.7±5.5)% degranulation",
"(6.9±3.4)% degranulation",
"(12.5±5.6)% degranulation",
" (17.6±6.1)% degranulation",
"(11.3±1.7)% degranulation",
                    }

LITTLE_HEMOLYTIC2 = list(["%s" % str(n) + "% Hemolysis" for n in range(0, 20)])
LITTLE_HEMOLYTIC3 = list(["%s" % str(n) + "% Cell Death" for n in range(0, 20)])
LITTLE_HEMOLYTIC4 = list(["%s" % str(n) + "% Cytotoxicity" for n in range(0, 20)])
LITTLE_HEMOLYTIC5 = list(["%s" % str(n) + "% cytotoxicity" for n in range(0, 20)])
LITTLE_HEMOLYTIC6 = list(["%s" % str(n) + "% Killing" for n in range(0, 20)])
LITTLE_HEMOLYTIC7 = list(["%s" % str(n) + "% cell death" for n in range(0, 20)])
LITTLE_HEMOLYTIC8 = list(["%s" % str(n) + "% Inhibition" for n in range(0, 20)])
LITTLE_HEMOLYTIC9 = list(["%s" % str(n) + "% degranulation" for n in range(0, 20)])
LITTLE_HEMOLYTIC = list(LITTLE_HEMOLYTIC) + LITTLE_HEMOLYTIC2 + LITTLE_HEMOLYTIC3 + LITTLE_HEMOLYTIC4 + LITTLE_HEMOLYTIC5 +  LITTLE_HEMOLYTIC6+LITTLE_HEMOLYTIC7 +LITTLE_HEMOLYTIC8 +LITTLE_HEMOLYTIC9
LITTLE_HEMOLYTIC = set(LITTLE_HEMOLYTIC)


NO_HEMOLYTIC = {"Lacks hemolytic activity",
                "nonhemolytic",
                "Has no hemolytic activity",
                "but no hemolytic activity",
                "Displays no hemolytic activity",
                "No hemolytic activity has been detected",
                "has no hemolytic activity",
                "Show little or no hemolytic activity",
                "did not exhibit significant hemolytic activity",
                "No hemolytic activity",
                "is devoid of hemolytic activity",
                "Has no or very limited (<3%) hemolytic activity",
                "Does not show significant hemolytic activity",
                "Does not have hemolytic activity",
                "not hemolytic",
                "Has a non-hemolytic activity",
                "does not possess hemolytic activity",
                "Non-hemolytic",
                "No hemolytic",
                "non-hemolytic",
                "no hemolytic",
                "Any appreciable hemolytic activity is not observed",
                "Does not cause hemolysis",
                "no hemolysis",
                "Does not show hemolytic activity.",
                "Does not have hemolytic",
                "without hemolytic activity",
                "No significant hemolytic activity",
                "No antibacterial, antifungal and hemolytic activities",
                "did not cause any hemolysis",
                "complete loss of hemolysis activity",
                "does not exhibit hemolytic activity",
                "no adverse effect on red blood cells",
                "0% hemolysis",
                "No hemolysis",
                "0.1 hemolytic",
                "Weak hemolysis",
                "negligible hemolytic activity",
                "Not detected hemolysis",
                "0% Hemolysis",
                "-",
                "<1%  Hemolysis",
                }


YES_HEMOLYTIK = {"IC50", "LD50", "ED50", "LC50", "MHC", "HD50", "EC50", "HC50",
                 "EC25", "HC10", "HL50", "HU",
                 "Area of inhibition",
                 "Conc. Required for hemolysis",
                 "Lethal concentration",
                 "zone of inhibition",
                 "Hemolytic activity i.e.",
                 "can totally lyse",
                 "Hemolytic at ",
                 "Hemolytic 645µM",
                 "Hemolytic activity expresssed as the initial rate",
                 
                 "0.25 fractions hemolyis",
                 
                 }

LITTLE_HEMOLYTIK = {
        "~10% hemolsis",
                 "4.78% Hmolysis",
                 "5.13%hemolysis",
                 ">2-3% at ≥16μM",
                 ">2-3% at ≥20μM",
                 "1.5 ±1.4%hemolytic at 100μM",
                 "-1.2 ± 2.6%hemolytic at 100μM",
                 "-0.4 ± 0.5%hemolytic at 100μM",
                 "0.01 fracions Hemoysis",
                 }

NO_HEMOLYTIK = {"Inactive",
                "No or little hemolysis",
                "negligible hemolysis",
                "0.0 fractions hemolysis",
                }
